name: Static Analysis
run-name: Static Analysis
on: [push]
jobs:
  Code-Complexity:
    runs-on: self-hosted
    steps:
      - run: echo "Job is running on a ${{ runner.os }} runner"
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Fetch git submodules
        run: |
          git submodule update --init --recursive
          git submodule foreach git checkout
      - run: echo "The ${{ github.repository }} repository has been cloned to the runner."
      - name: Files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Run static analysis of code complexity
        run: |
          chmod +x Scripts/run_lizard.sh
          Scripts/run_lizard.sh